language: java

env:
  global:
    - secure: "A2eTgU2l8t+ubPgBhT556TI1lokJY4rtPQE7XEGk3zTnyh70Ro5r30Dm/A3P\nr2a4Fn1dWG+tRkDwk/tKhvBmZ15UGaMY4up3NAMbGdKstJMV89r6dVkYcas7\nYAyLJi/KPXt66iuFaX3Hzsg521f3x5Sw/qV3s5Ot/EVbdMLUHNA="
    - secure: "heUWICMwovhcNdyxAU/9hABZEfh5tuyZL/FvbWIfday/NFlaTfbOix/oyyBW\nnKD14/CgHEG75Zv/knUjC9C5DCu/JmK455gzWkl91SzcNtM8HX4z2kUVMnJS\nvWPP2BiNklXc0ETjWwmJodAH9bJqDbABrj4au3zUbxc657Zg27c="
    
after_success:
  - python travis/addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml